### ISSUE TITLE
Bug with save skins with skins from Markedplace

### ISSUE THREAD

**Issue by galaxytwenty** [HimbeersaftLP/LibSkin#6]
For example the wandering trader!

This is the skin it looks when im joining in to the server:

![skinOnJoin](https://user-images.githubusercontent.com/79281788/227178014-5db0155b-189f-4dff-b8f0-fa0eb9a0afa6.PNG)

This is the skin it looks when im runnin /skin save and then /skin load:
![SkinOnLoadSkin](https://user-images.githubusercontent.com/79281788/227178235-5faffaa5-048b-4585-bf03-60999b7108a8.PNG)

And this is the saved skin texture from plugin_data:
![Razor8I9I](https://user-images.githubusercontent.com/79281788/227178433-240937cd-0fa1-4fec-89bc-8af5951b24d6.png)

This is only with some skins from markedplace, and not with downloaded skins.

**Comment by galaxytwenty** [comment]
Screenshot from this content from markedplace:
![marketPlace](https://user-images.githubusercontent.com/79281788/227179123-b3fa7337-e3a7-47ae-92a6-6c0397714dce.PNG)

**Comment by galaxytwenty** [comment]
I dont think so, if i save the geo and set the geo when load skin ... its exactly the same..

aaand he save the skin wrong in .png

**Comment by HimbeersaftLP** [comment]
can you send me the player.dat file so i can look at the raw skin data?

**Comment by HimbeersaftLP** [comment]
(the player.dat file before overwriting with the wrong skin using my library ofc)

**Comment by galaxytwenty** [comment]
Sure i can send when im home,You mean the Player.dat after joining with the skin, before i run save and load , right?Am 24.03.23, 19:43 schrieb Himbeer ***@***.***>:

   
  (the player.dat file before overwriting with the wrong skin using my library ofc)

**Comment by galaxytwenty** [comment]
can i send via DC?

**Comment by HimbeersaftLP** [comment]
yes exactly and I think you can upload it right here on github

**Comment by galaxytwenty** [comment]
sure, i can try uploading here.

**Comment by galaxytwenty** [comment]
must ziping the .dat... GH say we dont support that file type

**Comment by galaxytwenty** [comment]
[glx20.zip](https://github.com/HimbeersaftLP/LibSkin/files/11068627/glx20.zip)

**Comment by galaxytwenty** [comment]
there is the player.dat directly after joinen with the wandering trader skin

**Comment by HimbeersaftLP** [comment]
Thanks, I'll take a look at it

**Comment by galaxytwenty** [comment]
np, hopefully it can be fixed :)

**Comment by galaxytwenty** [comment]
have you found any points in these file ?

**Comment by HimbeersaftLP** [comment]
Sorry I didn't have time, yet

**Comment by HimbeersaftLP** [comment]
Hello, I found the problem.

You will need to save and restore both the geometry and the geometry name.

As an example, I updated the example plugin like this to include that change:
https://github.com/HimbeersaftLP/LibSkin/commit/4f1a9369fbd737b09e2a9e88d981cad03916836e#diff-fdfadedddd0afa2f4f19afd620913f573521b6d7ed08a168b8bcd376b2b82594

**Comment by HimbeersaftLP** [comment]
@galaxytwenty Please let my know if this fix works for you as well

**Comment by galaxytwenty** [comment]
Of course, i testing this when im home.I let you know. Thanks

**Comment by galaxytwenty** [comment]
Thats work´s fine now.
Best Thanks :)

**Comment by HimbeersaftLP** [comment]
You're welcome!

**Comment by HimbeersaftLP** [comment]
Thanks for testing it

**Comment by galaxytwenty** [comment]
Thanks for i can use it 👍
